title: Esdrasite
description: >- # this means to ignore newlines until "baseurl:"
  Um blog moderno e fluido para postagens de mensagens e artigos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ezrafchev.github.io/esdrasite" # the base hostname & protocol for your site
theme: minima

# Blog settings
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
permalink: pretty

# Blog settings
paginate: 5
paginate_path: "/page:num/"
