title: Esdrasite
description: >- # this means to ignore newlines until "baseurl:"
  Um blog moderno e fluido para postagens de mensagens e artigos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ezrafchev.github.io/esdrasite" # the base hostname & protocol for your site
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist
  - jekyll-github-metadata

# Blog settings
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "blog"
      type: ""
    values:
      layout: "home"


