title: Esdrasite
description: >- # this means to ignore newlines until "baseurl:"
  Um blog moderno e fluido para postagens de mensagens e artigos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ezrafchev.github.io/esdrasite" # the base hostname & protocol for your site
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-remote-theme
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Configurações do blog
paginate: 5
paginate_path: "/page:num/"

# Configurações de build
markdown: kramdown
permalink: pretty

# Configurações do tema
# Personalizações do tema
minimal_mistakes_skin: "air"
header:
  image: "background.mp4"
  caption: "Bem-vindo ao Esdrasite"
  actions:
    - label: "Leia mais"
      url: "/blog/"
      class: "btn--primary"
footer:
  links:
    - title: "Sobre"
      url: "/about/"
    - title: "Contato"
      url: "/contact/"
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist
  - jekyll-github-metadata

# Blog settings
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "blog"
      type: ""
    values:
      layout: "home"


